from fastapi import APIRouter
from src.model.MessageModel import MessageModel
from src.service.MessageService import MessageService

class ApiController:
    """
    This controller is responsible for setting up the API routes and handling
    the requests.
    """
    def __init__(self, app) -> None:
        router = APIRouter()
        self.messageService = MessageService()
        
        @router.post("/sendMessage")
        async def sendMessage(message: MessageModel) -> dict:
            """
            This route accepts a message input, performs a semantic search on the dataset,
            and returns a response generated by a local LLM based on the most relevant data.

            Args:
                message (MessageModel): The input message to be processed.

            Returns:
                dict: A dictionary containing the generated response from the LLM.
            """
            response = self.messageService.processMessage(message.message)

            return {"response": response}
        
        app.include_router(router)